language: python
sudo: false
matrix:
    include:
        - os: linux
          python: pypy
        - os: linux
          python: pypy3
          env: BUILOUT_OPTIONS=sphinx:eggs=
        - os: linux
          python: 2.7
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - python: 3.7
          dist: xenial
          sudo: true
install:
    - pip install -U pip
    - pip install -U setuptools zc.buildout
    - buildout $BUILOUT_OPTIONS
script:
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then bin/coverage run bin/coverage-test -v; fi
    - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then bin/test -v; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy3* ]]; then make -C doc html; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi # install early enough to get into the cache
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then bin/coverage combine; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
notifications:
    email: false
cache:
  directories:
    - $HOME/.cache/pip
    - eggs
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
