language: python
sudo: false
python:
    - pypy
    - pypy3
    - 2.7
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install zc.buildout
    - buildout
    - cd doc; make html
notifications:
    email: false
cache:
  directories:
    - eggs
