language: python
sudo: false
matrix:
    include:
        - os: linux
          python: pypy
        - os: linux
          python: pypy3
          env: BUILOUT_OPTIONS=sphinx:eggs=
        - os: linux
          python: 2.7
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
install:
    - pip install zc.buildout
    - buildout $BUILOUT_OPTIONS
script:
    - bin/test -v1j99
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then cd doc; make html; fi
notifications:
    email: false
cache:
  directories:
    - eggs
